print("Hola Mundo.py\n Hola Mundo.py\nHola Mundo.py\n")
print("Hola Mundo.py\n Hola Mundo.py\nHola Mundo.py\n")
print("Hola Mundo.py\n Hola Mundo.py\nHola Mundo.py\n")
print("Hola Mundo.py\n Hola Mundo.py\nHola Mundo.py\n")
print("Hola Mundo.py\n Hola Mundo.py\nHola Mundo.py\n")
print("Hola Mundo.py\n Hola Mundo.py\nHola Mundo.py\n")
print("Hola Mundo.py\n Hola Mundo.py\nHola Mundo.py\n")
print("Hola Mundo.py\n Hola Mundo.py\nHola Mundo.py\n")
print("Hola Mundo.py\n Hola Mundo.py\nHola Mundo.py\n")
print("Hola Mundo.py\n Holakmaximiliao san amrtin es uana bsorudex pero n sabe el jivel que yo tengo francisco se tira o pedo, el nivel que yo tengoMundo.py\nHola Mundo.py\n")
print("Hola Mundo.py\n Hola Mundo.py\nHola Mundo.py\n")
print("Hola Mundo.py\n Hola Mundo.py\nHola Mundo.pyuuymaxiilian san amrtin oorwue el frnacisco es muy pao y inutuo\n")